# Generated by Django 4.0.3 on 2022-03-13 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 17, 6, 42, 799994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 17, 6, 42, 798999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 17, 6, 42, 799994, tzinfo=utc)),
        ),
    ]
