# Generated by Django 4.0.3 on 2022-03-13 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_boss_birth_date_alter_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 17, 8, 14, 448552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 17, 8, 14, 447519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 17, 8, 14, 448552, tzinfo=utc)),
        ),
    ]
